In [5]:
import pandas as pd

In [6]:
data = pd.read_csv('F:/Pykih/SDG Data/SDG India Index with goal.csv')

In [22]:
data.head(1000)

,States_Uts,SDG,Population living below National Poverty line (%),Households with any usual member covered by any health scheme or health insurance (%),Persons provided employment as a percentage of persons who demanded employment under MGNREGA (%),Proportion of the population (out of total eligible population) receiving social protection benefits under Maternity Benefit,"Number of homeless households per 10,000 households","Ratio of rural households covered under public distribution system to rural households where monthly income of highest earning member is less than Rs.5,000",Children under age 5 years who are stunted (%),Pregnant women aged 15-49 yrs who are anaemic (11.0g/dl) (%),...,Total land area covered under forest (%),Decadal change in extent of water bodies within forests from 2005 to 2015 (%),Change in forest area from 2015 to 2017 (%),Change in estimated population of wild elephants over 5-year period (%),Reported murders per 1 lakh population,Reported cognizable crimes against children per 1 lakh population,Estimated number of courts per 10 Lakh persons,Estimated reported corruption crimes per 1 crore population,Births registered (%),Population covered under Aadhaar (%)
0,Target,1,10.95,100.0,100.00,100.0,0.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,India,1,21.92,28.7,84.75,36.4,10.39,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A & N Islands,1,1.00,5.7,92.46,1.4,0.97,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andhra Pradesh,1,9.20,74.6,87.77,17.4,15.34,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arunachal Pradesh,1,34.67,58.3,85.56,20.5,0.23,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Assam,1,31.98,10.4,87.10,66.1,3.42,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Bihar,1,33.74,12.3,75.63,53.9,3.13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Chandigarh,1,21.81,21.3,NaN,13.7,19.70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Chhattisgarh,1,39.93,68.5,77.25,66.2,15.77,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,D & N Haveli,1,39.31,30.8,NaN,2.6,24.94,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Daman and Diu,1,9.86,17.0,NaN,19.3,0.67,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Delhi,1,9.91,16.4,NaN,7.9,54.52,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Goa,1,5.09,15.9,98.15,7.4,1.62,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Gujarat,1,16.63,23.1,80.92,8.9,14.06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Haryana,1,11.16,12.2,80.16,13.5,14.52,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Himachal Pradesh,1,8.06,25.8,91.12,13.1,9.37,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Jammu and Kashmir,1,10.35,4.2,88.79,54.0,12.33,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Jharkhand,1,36.96,13.3,70.34,41.6,4.38,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Karnataka,1,20.91,28.1,84.26,19.9,8.45,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Kerala,1,7.05,47.7,87.98,20.4,3.40,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Lakshadweep,1,2.77,3.4,56.13,17.5,0.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Madhya Pradesh,1,31.65,17.7,79.68,61.1,21.42,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Maharashtra,1,17.35,15.0,86.40,8.7,17.18,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Manipur,1,36.89,3.6,96.46,26.2,2.95,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Meghalaya,1,11.87,34.6,97.30,28.0,4.24,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Mizoram,1,20.40,45.4,99.94,47.5,0.62,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Nagaland,1,18.88,6.1,98.91,29.7,3.03,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Odisha,1,32.59,47.7,84.76,72.6,7.11,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Puducherry,1,9.69,32.8,83.78,21.4,3.97,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Punjab,1,8.26,21.2,81.63,19.1,6.59,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,Chhattisgarh,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.7,47.2,12.09,452.20,100.0,94.1
465,D & N Haveli,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.2,16.2,7.32,NaN,73.7,97.2
466,Daman and Diu,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.2,34.4,28.41,NaN,78.8,96.6
467,Delhi,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.5,146.0,19.71,8.00,100.0,100.0
468,Goa,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.5,44.2,36.28,3.96,87.1,100.0
469,Gujarat,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.8,17.6,17.84,1677.24,98.7,95.5
470,Haryana,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.8,33.4,24.44,21.08,100.0,100.0
471,Himachal Pradesh,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.4,21.6,24.94,10.19,100.0,100.0
472,Jammu and Kashmir,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.1,4.9,9.52,75.51,76.3,73.1
473,Jharkhand,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.5,5.5,14.81,87.40,88.3,93.5
474,Karnataka,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.5,22.7,12.20,7.01,94.9,92.9
475,Kerala,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.9,30.8,12.00,65.53,98.1,100.0
476,Lakshadweep,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,25.0,NaN,NaN,69.6,98.6
477,Madhya Pradesh,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.6,45.7,7.57,111.31,77.3,90.1
478,Maharashtra,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.9,38.5,20.22,129.00,100.0,93.1
479,Manipur,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,14.0,6.94,0.00,100.0,80.7
480,Meghalaya,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.9,24.0,5.57,0.00,100.0,21.4
481,Mizoram,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.7,50.8,13.11,15.25,100.0,81.2
482,Nagaland,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.5,11.6,NaN,80.87,100.0,56.5
483,Odisha,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.1,23.4,11.51,2489.83,96.1,93.2
484,Puducherry,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,15.1,NaN,37.12,100.0,94.4
485,Punjab,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.6,21.0,24.13,38.18,99.2,100.0
486,Rajasthan,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.1,14.1,17.68,131.14,98.7,86.5
487,Sikkim,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.6,55.0,25.25,1.87,72.2,88.1
488,Tamil Nadu,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.3,14.1,9.53,2492.45,100.0,93.4
489,Telangana,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.8,26.0,8.31,NaN,94.6,100.0
490,Tripura,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.8,22.1,20.30,0.26,93.0,90.0
491,Uttar Pradesh,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.2,18.2,9.71,27.59,67.4,87.2
492,Uttarakhand,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.8,17.6,19.63,66.12,100.0,98.8
493,West Bengal,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.2,23.8,7.25,0.75,92.8,93.9

In [10]:
data1 = pd.melt(data, id_vars=["SDG", "States_Uts"], 
                  var_name="Indicator", value_name="Value")

In [11]:
data1.shape

(30628, 4)

In [12]:
data1.head(100)

,SDG,States_Uts,Indicator,Value
0,1,Target,Population living below National Poverty line (%),10.95
1,1,India,Population living below National Poverty line (%),21.92
2,1,A & N Islands,Population living below National Poverty line (%),1
3,1,Andhra Pradesh,Population living below National Poverty line (%),9.2
4,1,Arunachal Pradesh,Population living below National Poverty line (%),34.67
5,1,Assam,Population living below National Poverty line (%),31.98
6,1,Bihar,Population living below National Poverty line (%),33.74
7,1,Chandigarh,Population living below National Poverty line (%),21.81
8,1,Chhattisgarh,Population living below National Poverty line (%),39.93
9,1,D & N Haveli,Population living below National Poverty line (%),39.31
10,1,Daman and Diu,Population living below National Poverty line (%),9.86
11,1,Delhi,Population living below National Poverty line (%),9.91
12,1,Goa,Population living below National Poverty line (%),5.09
13,1,Gujarat,Population living below National Poverty line (%),16.63
14,1,Haryana,Population living below National Poverty line (%),11.16
15,1,Himachal Pradesh,Population living below National Poverty line (%),8.06
16,1,Jammu and Kashmir,Population living below National Poverty line (%),10.35
17,1,Jharkhand,Population living below National Poverty line (%),36.96
18,1,Karnataka,Population living below National Poverty line (%),20.91
19,1,Kerala,Population living below National Poverty line (%),7.05
20,1,Lakshadweep,Population living below National Poverty line (%),2.77
21,1,Madhya Pradesh,Population living below National Poverty line (%),31.65
22,1,Maharashtra,Population living below National Poverty line (%),17.35
23,1,Manipur,Population living below National Poverty line (%),36.89
24,1,Meghalaya,Population living below National Poverty line (%),11.87
25,1,Mizoram,Population living below National Poverty line (%),20.4
26,1,Nagaland,Population living below National Poverty line (%),18.88
27,1,Odisha,Population living below National Poverty line (%),32.59
28,1,Puducherry,Population living below National Poverty line (%),9.69
29,1,Punjab,Population living below National Poverty line (%),8.26
...,...,...,...,...
70,2,Tamil Nadu,Population living below National Poverty line (%),NaN
71,2,Telangana,Population living below National Poverty line (%),NaN
72,2,Tripura,Population living below National Poverty line (%),NaN
73,2,Uttar Pradesh,Population living below National Poverty line (%),NaN
74,2,Uttarakhand,Population living below National Poverty line (%),NaN
75,2,West Bengal,Population living below National Poverty line (%),NaN
76,3,Target,Population living below National Poverty line (%),NaN
77,3,India,Population living below National Poverty line (%),NaN
78,3,A & N Islands,Population living below National Poverty line (%),NaN
79,3,Andhra Pradesh,Population living below National Poverty line (%),NaN
80,3,Arunachal Pradesh,Population living below National Poverty line (%),NaN
81,3,Assam,Population living below National Poverty line (%),NaN
82,3,Bihar,Population living below National Poverty line (%),NaN
83,3,Chandigarh,Population living below National Poverty line (%),NaN
84,3,Chhattisgarh,Population living below National Poverty line (%),NaN
85,3,D & N Haveli,Population living below National Poverty line (%),NaN
86,3,Daman and Diu,Population living below National Poverty line (%),NaN
87,3,Delhi,Population living below National Poverty line (%),NaN
88,3,Goa,Population living below National Poverty line (%),NaN
89,3,Gujarat,Population living below National Poverty line (%),NaN
90,3,Haryana,Population living below National Poverty line (%),NaN
91,3,Himachal Pradesh,Population living below National Poverty line (%),NaN
92,3,Jammu and Kashmir,Population living below National Poverty line (%),NaN
93,3,Jharkhand,Population living below National Poverty line (%),NaN
94,3,Karnataka,Population living below National Poverty line (%),NaN
95,3,Kerala,Population living below National Poverty line (%),NaN
96,3,Lakshadweep,Population living below National Poverty line (%),NaN
97,3,Madhya Pradesh,Population living below National Poverty line (%),NaN
98,3,Maharashtra,Population living below National Poverty line (%),NaN
99,3,Manipur,Population living below National Poverty line (%),NaN

In [19]:
data2 =data1.groupby(['States_Uts', 'SDG','Indicator','Value']).agg(lambda col: ','.join(col)).reset_index()

In [20]:
type(data2)

pandas.core.frame.DataFrame

In [21]:
data2.head(50)

,States_Uts,SDG,Indicator,Value,0
0,A & N Islands,1,Households with any usual member covered by an...,5.7,"SDG,States_Uts,Indicator,Value"
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,"SDG,States_Uts,Indicator,Value"
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,"SDG,States_Uts,Indicator,Value"
3,A & N Islands,1,Population living below National Poverty line (%),1,"SDG,States_Uts,Indicator,Value"
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,"SDG,States_Uts,Indicator,Value"
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,"SDG,States_Uts,Indicator,Value"
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,"SDG,States_Uts,Indicator,Value"
7,A & N Islands,2,Ratio of rural households covered under public...,0.49,"SDG,States_Uts,Indicator,Value"
8,A & N Islands,2,"Rice, wheat and coarse cereals produced annual...",2211.38,"SDG,States_Uts,Indicator,Value"
9,A & N Islands,3,Annual notification of Tuberculosis cases per ...,76,"SDG,States_Uts,Indicator,Value"
10,A & N Islands,3,Children aged 12-23 months fully immunized (BC...,73.2,"SDG,States_Uts,Indicator,Value"
11,A & N Islands,3,"Number of governmental physicians, nurses and ...",16.43,"SDG,States_Uts,Indicator,Value"
12,A & N Islands,3,"Under-five mortality rate per 1,000 live births",13,"SDG,States_Uts,Indicator,Value"
13,A & N Islands,4,Adjusted Net Enrolment Ratio at Elementary (C...,77.48,"SDG,States_Uts,Indicator,Value"
14,A & N Islands,4,Average Annual Drop-out rate at secondary leve...,9.87,"SDG,States_Uts,Indicator,Value"
15,A & N Islands,4,Children in the age group of 6-13 who are out ...,2.12,"SDG,States_Uts,Indicator,Value"
16,A & N Islands,4,Correct responses on Learning Outcomes in Lang...,52,"SDG,States_Uts,Indicator,Value"
17,A & N Islands,4,Correct responses on Learning Outcomes in Lang...,39,"SDG,States_Uts,Indicator,Value"
18,A & N Islands,4,Elementary and secondary schools with Pupil Te...,99.51,"SDG,States_Uts,Indicator,Value"
19,A & N Islands,4,School teachers professionally qualified (%),98.86,"SDG,States_Uts,Indicator,Value"
20,A & N Islands,5,Average female to male ratio of average wages/...,1,"SDG,States_Uts,Indicator,Value"
21,A & N Islands,5,Married women aged 15-49 who have ever experie...,19.6,"SDG,States_Uts,Indicator,Value"
22,A & N Islands,5,Ratio of Female Labour force participation rat...,0.41,"SDG,States_Uts,Indicator,Value"
23,A & N Islands,5,Women in the age group of 15-49 years using mo...,50.8,"SDG,States_Uts,Indicator,Value"
24,A & N Islands,6,Annual ground water withdrawal against net ann...,0.98,"SDG,States_Uts,Indicator,Value"
25,A & N Islands,6,Districts verified to be Open Defecation Free (%),0,"SDG,States_Uts,Indicator,Value"
26,A & N Islands,6,Population having safe and adequate drinking w...,88.7,"SDG,States_Uts,Indicator,Value"
27,A & N Islands,6,Rural households with individual household toi...,100,"SDG,States_Uts,Indicator,Value"
28,A & N Islands,7,Households using Clean Cooking Fuel (%),63.5,"SDG,States_Uts,Indicator,Value"
29,A & N Islands,7,Renewable share of installed generating capaci...,22.77,"SDG,States_Uts,Indicator,Value"
30,A & N Islands,8,Annual growth rate of GDP per capita (at const...,7.06,"SDG,States_Uts,Indicator,Value"
31,A & N Islands,8,Average unemployment rate per 1000 persons for...,189.5,"SDG,States_Uts,Indicator,Value"
32,A & N Islands,8,Households with a bank account (%),100,"SDG,States_Uts,Indicator,Value"
33,A & N Islands,8,"Number of ATMs per 1,00,000 population",25.03,"SDG,States_Uts,Indicator,Value"
34,A & N Islands,9,Gram Panchayats covered under Bharat Net (%),0,"SDG,States_Uts,Indicator,Value"
35,A & N Islands,10,Palma Ratio of Household Expenditure in Rural ...,0.98,"SDG,States_Uts,Indicator,Value"
36,A & N Islands,10,Palma Ratio of Household Expenditure in Urban ...,1.76,"SDG,States_Uts,Indicator,Value"
37,A & N Islands,10,Tribal Sub Plan fund utilised (%),155.4,"SDG,States_Uts,Indicator,Value"
38,A & N Islands,11,Urban households living in slums (%),3.72,"SDG,States_Uts,Indicator,Value"
39,A & N Islands,11,Wards with 100% door to door waste collection (%),100,"SDG,States_Uts,Indicator,Value"
40,A & N Islands,11,Waste processed (%),23,"SDG,States_Uts,Indicator,Value"
41,A & N Islands,15,Change in estimated population of wild elephan...,Null,"SDG,States_Uts,Indicator,Value"
42,A & N Islands,15,Change in forest area from 2015 to 2017 (%),-0.11,"SDG,States_Uts,Indicator,Value"
43,A & N Islands,15,Decadal change in extent of water bodies withi...,-15.14,"SDG,States_Uts,Indicator,Value"
44,A & N Islands,15,Total land area covered under forest (%),81.73,"SDG,States_Uts,Indicator,Value"
45,A & N Islands,16,Births registered (%),79.3,"SDG,States_Uts,Indicator,Value"
46,A & N Islands,16,Estimated number of courts per 10 Lakh persons,28.05,"SDG,States_Uts,Indicator,Value"
47,A & N Islands,16,Estimated reported corruption crimes per 1 cro...,0.3,"SDG,States_Uts,Indicator,Value"
48,A & N Islands,16,Population covered under Aadhaar (%),95,"SDG,States_Uts,Indicator,Value"
49,A & N Islands,16,Reported cognizable crimes against children pe...,61.4,"SDG,States_Uts,Indicator,Value"

In [10]:
data2.columns

Index(['States_Uts', 'SDG', 'Indicator', 'Value', 0], dtype='object')

In [11]:
data3=data2.drop([0], axis=1)

In [12]:
data3.shape

(2174, 4)

In [13]:
mapping = {1:'No Poverty', 2:'Zero Hunger', 3:'Good Health and Well-Being',  4:'Quality Education', 5:'Gender Equality',
           6:'Clean Water and Sanitation',7:'Affordable and Clean Energy',8:'Decent Work and Economic Growth',
           9:'Industry Innovation and Infrastructure',10:'Reduced Inequalities',11:'Sustainable Cities and Communities',
          15:'Life on Land',16:'Peace Justice and Strong Institutions'}

In [14]:
data3['SDG GoalShort'] = data3['SDG'].map(mapping)

In [15]:
data3.head(50)

,States_Uts,SDG,Indicator,Value,SDG GoalShort
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger
7,A & N Islands,2,Ratio of rural households covered under public...,0.49,Zero Hunger
8,A & N Islands,2,"Rice, wheat and coarse cereals produced annual...",2211.38,Zero Hunger
9,A & N Islands,3,Annual notification of Tuberculosis cases per ...,76,Good Health and Well-Being
10,A & N Islands,3,Children aged 12-23 months fully immunized (BC...,73.2,Good Health and Well-Being
11,A & N Islands,3,"Number of governmental physicians, nurses and ...",16.43,Good Health and Well-Being
12,A & N Islands,3,"Under-five mortality rate per 1,000 live births",13,Good Health and Well-Being
13,A & N Islands,4,Adjusted Net Enrolment Ratio at Elementary (C...,77.48,Quality Education
14,A & N Islands,4,Average Annual Drop-out rate at secondary leve...,9.87,Quality Education
15,A & N Islands,4,Children in the age group of 6-13 who are out ...,2.12,Quality Education
16,A & N Islands,4,Correct responses on Learning Outcomes in Lang...,52,Quality Education
17,A & N Islands,4,Correct responses on Learning Outcomes in Lang...,39,Quality Education
18,A & N Islands,4,Elementary and secondary schools with Pupil Te...,99.51,Quality Education
19,A & N Islands,4,School teachers professionally qualified (%),98.86,Quality Education
20,A & N Islands,5,Average female to male ratio of average wages/...,1,Gender Equality
21,A & N Islands,5,Married women aged 15-49 who have ever experie...,19.6,Gender Equality
22,A & N Islands,5,Ratio of Female Labour force participation rat...,0.41,Gender Equality
23,A & N Islands,5,Women in the age group of 15-49 years using mo...,50.8,Gender Equality
24,A & N Islands,6,Annual ground water withdrawal against net ann...,0.98,Clean Water and Sanitation
25,A & N Islands,6,Districts verified to be Open Defecation Free (%),0,Clean Water and Sanitation
26,A & N Islands,6,Population having safe and adequate drinking w...,88.7,Clean Water and Sanitation
27,A & N Islands,6,Rural households with individual household toi...,100,Clean Water and Sanitation
28,A & N Islands,7,Households using Clean Cooking Fuel (%),63.5,Affordable and Clean Energy
29,A & N Islands,7,Renewable share of installed generating capaci...,22.77,Affordable and Clean Energy
30,A & N Islands,8,Annual growth rate of GDP per capita (at const...,7.06,Decent Work and Economic Growth
31,A & N Islands,8,Average unemployment rate per 1000 persons for...,189.5,Decent Work and Economic Growth
32,A & N Islands,8,Households with a bank account (%),100,Decent Work and Economic Growth
33,A & N Islands,8,"Number of ATMs per 1,00,000 population",25.03,Decent Work and Economic Growth
34,A & N Islands,9,Gram Panchayats covered under Bharat Net (%),0,Industry Innovation and Infrastructure
35,A & N Islands,10,Palma Ratio of Household Expenditure in Rural ...,0.98,Reduced Inequalities
36,A & N Islands,10,Palma Ratio of Household Expenditure in Urban ...,1.76,Reduced Inequalities
37,A & N Islands,10,Tribal Sub Plan fund utilised (%),155.4,Reduced Inequalities
38,A & N Islands,11,Urban households living in slums (%),3.72,Sustainable Cities and Communities
39,A & N Islands,11,Wards with 100% door to door waste collection (%),100,Sustainable Cities and Communities
40,A & N Islands,11,Waste processed (%),23,Sustainable Cities and Communities
41,A & N Islands,15,Change in estimated population of wild elephan...,Null,Life on Land
42,A & N Islands,15,Change in forest area from 2015 to 2017 (%),-0.11,Life on Land
43,A & N Islands,15,Decadal change in extent of water bodies withi...,-15.14,Life on Land
44,A & N Islands,15,Total land area covered under forest (%),81.73,Life on Land
45,A & N Islands,16,Births registered (%),79.3,Peace Justice and Strong Institutions
46,A & N Islands,16,Estimated number of courts per 10 Lakh persons,28.05,Peace Justice and Strong Institutions
47,A & N Islands,16,Estimated reported corruption crimes per 1 cro...,0.3,Peace Justice and Strong Institutions
48,A & N Islands,16,Population covered under Aadhaar (%),95,Peace Justice and Strong Institutions
49,A & N Islands,16,Reported cognizable crimes against children pe...,61.4,Peace Justice and Strong Institutions

In [16]:
metadata= pd.read_csv('F:/Pykih/SDG Data/sdg_index_meta.csv')

In [17]:
metadata.head(50)

,SNO,Goal,Indicator,Indicator Data Source,Computation Approach,Data Period,Number of States/UTs covered,Data Periodicity,Relevant UN Target,Relevant UN Indicator,Relevant MoSPI Indicator,Indicator Interpretation,Code
0,1,SDG 1 - End poverty in all its forms everywhere,Percentage of population living below National...,NITI Aayog [Tendulkar Committee Estimates],Directly from data source,2011-2012,35,Non-Periodic,"1.2: By 2030, reduce at least by half the prop...",1.2.1: Proportion of population living below t...,1.1.1: Proportion of population living below t...,Higher value means lower performance (-),1.1.1
1,2,SDG 1 - End poverty in all its forms everywhere,Percentage of households with any usual member...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,1.3: Implement nationally appropriate social p...,1.3.1: Proportion of population covered by soc...,1.3.1: Percentage of households with any usual...,Higher value means higher performance (+),1.3.1
2,3,SDG 1 - End poverty in all its forms everywhere,Persons provided employment as a percentage of...,Ministry of Rural Development [MGNREGA Progres...,(Persons provided employment under MGNREGA)×10...,2017-18,32,Annual,1.3: Implement nationally appropriate social p...,1.3.1: Proportion of population covered by soc...,1.3.3: Proportion of the population (out of to...,Higher value means higher performance (+),1.3.3
3,4,SDG 1 - End poverty in all its forms everywhere,Proportion of the population (out of total eli...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,1.3: Implement nationally appropriate social p...,1.3.1: Proportion of population covered by soc...,1.3.5: Proportion of the population (out of to...,Higher value means higher performance (+),1.3.5
4,5,SDG 1 - End poverty in all its forms everywhere,"Number of homeless households per 10,000 house...",Numerator: Ministry of Rural Development [Soci...,"Number of homeless households per 10,000 house...",2011-12,36,10 Years,"1.4: By 2030, ensure that all men and women, i...",NaN,1.4.4: Proportion of homeless population to to...,Higher value means lower performance (-),1.4.4
5,6,"SDG 2 - End hunger, achieve food security and ...",Ratio of rural households covered under public...,\nNumerator: Planning Commission[Planning Comm...,\n(Percentage of rural households covered unde...,2011-12,36,10 Years,"2.1: By 2030, end hunger and ensure access by ...",2.1.2: Prevalence of moderate or severe food i...,2.1.2: Proportion of Population (marginalized ...,Higher value means higher performance (+),2.1.2
6,7,"SDG 2 - End hunger, achieve food security and ...",Percentage of children under age 5 years who a...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,"2.2: By 2030, end all forms of malnutrition, i...",2.2.1: Prevalence of stunting (height for age ...,2.2.1: Percentage of Children under age 5 year...,Higher value means lower performance (-),2.2.1
7,8,"SDG 2 - End hunger, achieve food security and ...",Percentage of pregnant women aged 15-49 years ...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,34,3 Years,"2.2: By 2030, end all forms of malnutrition, i...",NaN,2.2.4: Percentage of Pregnant women age 15-49 ...,Higher value means lower performance (-),2.2.4
8,9,"SDG 2 - End hunger, achieve food security and ...","Rice, wheat and coarse cereals produced annual...",Ministry of Agriculture and Farmers Welfare [M...,"\n(Total weight of rice,wheat and coarse cerea...",2015-16,36,Annual,"2.3: By 2030, double the agricultural producti...",2.3.1: Volume of production per labour unit by...,2.3.1: Agriculture productivity of Wheat and R...,Higher value means higher performance (+),2.3.1
9,10,SDG 3: Ensure Healthy Lives and Well-Being for...,Maternal Mortality Ratio,Ministry of Home Affairs [Sample Registration ...,Directly from data source,2014-16,19,3 Years,"3.1: By 2030, reduce the global maternal morta...",3.1.1: Maternal mortality ratio,3.1.1: Maternal mortality ratio,Higher value means lower performance (-),3.1.1
10,11,SDG 3: Ensure Healthy Lives and Well-Being for...,"Under-five mortality rate per 1,000 live births",Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,35,3 Years,"3.2: By 2030, end preventable deaths of newbor...",3.2.1: Under-five mortality rate,3.2.1: Under-five mortality rate,Higher value means lower performance (-),3.2.1
11,12,SDG 3: Ensure Healthy Lives and Well-Being for...,Percentage of children aged 12-23 months fully...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,"3.2: By 2030, end preventable deaths of newbor...",NaN,3.2.3: Percentage of children aged 12-23 month...,Higher value means higher performance (+),3.2.3
12,13,SDG 3: Ensure Healthy Lives and Well-Being for...,Annual notification of Tuberculosis cases per ...,Ministry of Health and Family Welfare [India T...,Directly from data source,2016-17,36,Annual,"3.3: By 2030, end the epidemics of AIDS, tuber...","3.3.2: Tuberculosis incidence per 100,000 popu...","3.3.2: Tuberculosis incidence per 100,000 popu...",Higher value means lower performance (-),3.3.2
13,14,SDG 3: Ensure Healthy Lives and Well-Being for...,"Number of governmental physicians, nurses and ...",Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,35,3 Years,"3.8: Achieve universal health coverage, includ...",NaN,"3.8.8: Total physicians, nurses and midwives p...",Higher value means Higher performance (+),3.8.8
14,15,SDG 4: Ensure inclusive and equitable quality ...,Adjusted Net Enrolment Ratio at Elementary (Cl...,National Institute of Education Planning and I...,(Adjusted net enrolment ratio at elementary sc...,2016-17,36,Annual,"4.1: By 2030, ensure that all girls and boys c...",NaN,4.1.2: Adjusted net enrolment ratio in primary...,Higher value means higher performance (+),4.1.2
15,16,SDG 4: Ensure inclusive and equitable quality ...,Percentage correct responses on Learning Outco...,Ministry of Human Resource Development-Nationa...,Directly from data source,2016-17,36,2 Years,"4.1: By 2030, ensure that all girls and boys c...",4.1.1: Proportion of children and young people...,"4.1.4: Percentage of students in grade 3, 5, 8...",Higher value means higher performance (+),4.1.4
16,17,SDG 4: Ensure inclusive and equitable quality ...,Percentage correct responses on Learning Outco...,Ministry of Human Resource Development-Nationa...,Directly from data source,2016-17,36,2 Years,"4.1: By 2030, ensure that all girls and boys c...",4.1.1: Proportion of children and young people...,"4.1.4: Percentage of students in grade 3, 5, 8...",Higher value means higher performance (+),4.1.4
17,18,SDG 4: Ensure inclusive and equitable quality ...,Percentage of children in the age group of 6-1...,Ministry of Human Resource Development-Social ...,Directly from data source,2014,34,4 Years,"4.1: By 2030, ensure that all girls and boys c...",NaN,"4.1.7: Out of school ratio (primary, upper pri...",Higher value means lower performance (-),4.1.7
18,19,SDG 4: Ensure inclusive and equitable quality ...,Average Annual Drop-out rate at secondary leve...,Ministry of Human Resource Development [Minist...,Directly from data source,2015-16,35,2 Years,"4.1: By 2030, ensure that all girls and boys c...",NaN,NaN,Higher value means lower performance (-),NaN
19,20,SDG 4: Ensure inclusive and equitable quality ...,Percentage of school teachers professionally q...,National Institute of Education Planning and I...,Directly from data source,2016-17,36,2 Years,"4.c: By 2030, substantially increase the suppl...",4.c.1: Proportion of teachers in: (a) pre-prim...,"4.c.1: Proportion of trained teachers, by educ...",Higher value means higher performance (+),4.c.1
20,21,SDG 4: Ensure inclusive and equitable quality ...,Percentage of elementary and secondary schools...,National Institute of Education Planning and I...,Directly from data source,2016-17,36,2 Years,"4.c: By 2030, substantially increase the suppl...",NaN,4.c.2: Pupil/trained teacher ratio by educatio...,Higher value means higher performance (+),4.c.2
21,22,SDG 5: Achieve gender equality and empower all...,Sex Ratio at Birth (female per 1000 male),Ministry of Home Affairs-ORGI [Sample Registra...,Directly from data source,2014-16,22,3 Years,5.1: End all forms of discrimination against a...,NaN,5.1.3: Sex Ratio at Birth,Higher value means higher performance (+),5.1.3
22,23,SDG 5: Achieve gender equality and empower all...,Average female to male ratio of average wages/...,Ministry of Statistics and Programme Implement...,Average of urban and rural wages/salaries rece...,2011-12,35,5 Years,5.1: End all forms of discrimination against a...,NaN,NaN,Higher value means higher performance (+),NaN
23,24,SDG 5: Achieve gender equality and empower all...,Percentage of ever married women aged 15-49 wh...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,5.2: Eliminate all forms of violence against a...,5.2.1: Proportion of ever-partnered women and ...,5.2.3: Proportion of cruelty/ physical violenc...,Higher value means lower performance (-),5.2.3
24,25,SDG 5: Achieve gender equality and empower all...,Percentage of seats won by women in the genera...,Election Commission of India [Electoral Statis...,Directly from data source,2016-17,30,Annual,5.5: Ensure women's full and effective partici...,5.5.1: Proportion of seats held by women in (a...,5.5.1: Proportion of seats held by women in na...,Higher value means Higher performance (+),5.5.1
25,26,SDG 5: Achieve gender equality and empower all...,Ratio of Female Labour force participation rat...,Labour Bureau [Labour Bureau Report],(Female Labour force participation rate )/(Mal...,2015-16,35,Annual,5.5: Ensure women's full and effective partici...,NaN,NaN,Higher value means higher performance (+),NaN
26,27,SDG 5: Achieve gender equality and empower all...,Percentage of women in the age group of 15-49 ...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,5.6: Ensure universal access to sexual and rep...,5.6.1: Proportion of women aged 15-49 years wh...,5.6.1: Percentage of Currently married women (...,Higher value means higher performance (+),5.6.1
27,28,SDG 6: Ensure availability and sustainable man...,Percentage of population having safe and adequ...,Ministry of Drinking Water and Sanitation [Nat...,Directly from data source,2018,31,Annual,"6.1: By 2030, achieve universal and equitable ...",6.1.1: Proportion of population using safely m...,6.1.1: Percentage of population having safe an...,Higher value means higher performance (+),6.1.1
28,29,SDG 6: Ensure availability and sustainable man...,Percentage of rural households with individual...,Ministry of Drinking water and Sanitation [Swa...,Directly from data source,March 2018,34,Daily,"6.2: By 2030, achieve access to adequate and e...",6.2.1: Proportion of population using safely m...,6.2.1: Proportion of households having access ...,Higher value means higher performance (+),6.2.1
29,30,SDG 6: Ensure availability and sustainable man...,Percentage of districts verified to be Open De...,Ministry of Housing and Urban Affairs [Swachh ...,Directly from data source,March 2018,34,Daily,"6.2: By 2030, achieve access to adequate and e...",NaN,6.2.2: Percentage of Districts achieving Open...,Higher value means higher performance (+),6.2.2
30,31,SDG 6: Ensure availability and sustainable man...,Installed sewage treatment capacity as a propo...,"Ministry of Environment, Forest and Climate Ch...",Directly from data source,2016,29,Non-Periodic,"6.2: By 2030, achieve access to adequate and e...",NaN,NaN,Higher value means higher performance (+),NaN
31,32,SDG 6: Ensure availability and sustainable man...,Percentage annual ground water withdrawal agai...,Ministry of Water Resources [Dynamic Ground Wa...,Directly from data source,2012-13,35,5 Years,"6.4: By 2030, substantially increase water-use...",6.4.1: Change in water-use efficiency over time,6.4.1: Percentage Ground Water withdrawal agai...,Higher value means lower performance (-),6.4.1
32,33,"SDG 7: Ensure access to affordable, reliable, ...",Percentage of households electrified,Ministry of Power [Saubhagya Dashboard],Directly from data source,October 2018,30,Daily,"7.1: By 2030, ensure universal access to affor...",7.1.1: Proportion of population with access to...,7.1.1: Percentage of Households electrified,Higher value means higher performance (+),7.1.1
33,34,"SDG 7: Ensure access to affordable, reliable, ...",Percentage of households using Clean Cooking Fuel,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,"7.1: By 2030, ensure universal access to affor...",7.1.2: Proportion of population with primary r...,7.1.2: Percentage of household using clean coo...,Higher value means higher performance (+),7.1.2
34,35,"SDG 7: Ensure access to affordable, reliable, ...",Renewable share of installed generating capaci...,Ministry of Statistics and Programme Implement...,Directly from data source,2017,36,Annual,"7.2: By 2030, increase substantially the share...",7.2.1: Renewable energy share in the total fin...,7.2.1: Renewable energy share in the total fin...,Higher value means higher performance (+),7.2.1
35,36,"SDG 8: Promote sustained, inclusive and sustai...",Annual growth rate of GDP per capita (at const...,Ministry of Statistics and Programme Implement...,Directly from data source,2017-18,32,Annual,8.1: Sustain per capita economic growth in acc...,8.1.1: Annual growth rate of real GDP per capita,8.1.1: Annual growth rate of GDP (adjusted to ...,Higher value means higher performance (+),8.1.1
36,37,"SDG 8: Promote sustained, inclusive and sustai...",Average unemployment rate per 1000 persons for...,Labour Bureau [Labour Bureau Report],Directly from data source,2015-16,36,Annual,"8.5: By 2030, achieve full and productive empl...","8.5.2: Unemployment rate, by sex, age and pers...",8.5.1: Unemployment rate,Higher value means lower performance (-),8.5.1
37,38,"SDG 8: Promote sustained, inclusive and sustai...",Percentage of households with a bank account,Ministry of Finance [Progress Report on Pradha...,Directly from data source,2018,36,Weekly,8.10: Strengthen the capacity of domestic fina...,8.10.2: Proportion of adults (15 years and old...,8.10.2: Proportion of population having Bank a...,Higher value means higher performance (+),8.10.
38,39,"SDG 8: Promote sustained, inclusive and sustai...","Number of ATMs per 1,00,000 population",Reserve Bank of India [RBI Reports],Directly from data source,2018,36,3 Months,8.10: Strengthen the capacity of domestic fina...,8.10.1: (a) Number of commercial bank branches...,8.10.4: Automated Teller Machines (ATMs) per 1...,Higher value means higher performance (+),8.10.
39,40,"SDG 9: Build resilient infrastructure, promote...",Percentage of targeted habitations connected b...,National Rural Roads Development Organisation ...,Directly from data source,2017-18,29,Monthly,"9.1: Develop quality, reliable, sustainable an...",9.1.1: Proportion of the rural population who ...,9.1.1: Proportion of the rural population who...,Higher value means higher performance (+),9.1.1
40,41,"SDG 9: Build resilient infrastructure, promote...",Number of mobile connections per 100 persons i...,Numerator: Ministry of Communications - Depart...,Number of mobile connections per 100 persons i...,2016-2017,18,Annual,9.c: Significantly increase access to informat...,9.c.1: Proportion of population covered by a m...,9.c.1: Proportion of population covered by a ...,Higher value means higher performance (+),9.c.1
41,42,"SDG 9: Build resilient infrastructure, promote...",Number of Internet Subscribers per 100 population,Telecom Regulatory Authority of India [The Ind...,Directly from data source,June 2017,18,Annual,9.c: Significantly increase access to informat...,NaN,9.c.2: No. of Broadband Subscribers per 10000 ...,Higher value means higher performance (+),9.c.2
42,43,"SDG 9: Build resilient infrastructure, promote...",Percentage of Gram Panchayats covered under Bh...,Numerator: Department of Telecommunications[Do...,Percentage of Gram Panchayats covered under Bh...,2016-17,29,Annual,9.c: Significantly increase access to informat...,NaN,NaN,Higher value means higher performance (+),NaN
43,44,SDG 10: Reduce inequality within and among cou...,Palma Ratio based on Household Expenditure in ...,Numerator: Ministry of Statistics and Programm...,Ratio of total monthly consumption expenditure...,2011,35,10 Years,"10.1: By 2030, progressively achieve and susta...",NaN,10.1.2: Gini Coefficient of Household Expenditure,Higher value means lower performance (-),10.1.2
44,45,SDG 10: Reduce inequality within and among cou...,Palma Ratio based on Household Expenditure in ...,Numerator: Ministry of Statistics and Programm...,Ratio of total monthly consumption expenditure...,2011,35,10 Years,"10.1: By 2030, progressively achieve and susta...",NaN,10.1.2: Gini Coefficient of Household Expenditure,Higher value means lower performance (-),10.1.2
45,46,SDG 10: Reduce inequality within and among cou...,Ratio of Transgender Labour force participatio...,Labour Bureau [Labour Bureau Report],(Transgender Labour force participation rate )...,2015-16,27,Annual,"10.2: By 2030, empower and promote the social,...",NaN,NaN,Higher value means higher performance (+),NaN
46,47,SDG 10: Reduce inequality within and among cou...,Percentage of Scheduled Caste Sub Plan fund ut...,NITI Aayog [State Reports to NITI Aayog],Directly from data source,2013-14,25,Non-Periodic,"10.4: Adopt policies, especially fiscal, wage ...",NaN,NaN,Higher value means higher performance (+),NaN
47,48,SDG 10: Reduce inequality within and among cou...,Percentage of Tribal Sub Plan fund utilised,NITI Aayog [State Reports to NITI Aayog],Directly from data source,2013-14,22,Non-Periodic,"10.4: Adopt policies, especially fiscal, wage ...",NaN,NaN,Higher value means higher performance (+),NaN
48,49,SDG 11: Make cities and human settlements incl...,Houses completed under PMAY as a percentage of...,Ministry of Rural Development [Pradhan Mantri ...,Directly from data source,2018,34,Quarterly,"11.1: By 2030, ensure access for all to adequa...",NaN,11.1.1: Percentage of slums/Economically Weake...,Higher value means higher performance (+),11.1.1
49,50,SDG 11: Make cities and human settlements incl...,Percentage of urban households living in slums,Ministry of Home Affairs [Census 2011],Directly from data source,2011,31,10 Years,"11.1: By 2030, ensure access for all to adequa...",11.1.1: Proportion of urban population living ...,11.1.3: Proportion of Urban Population Living ...,Higher value means lower performance (-),11.1.3

In [18]:
a = metadata.Goal.unique()

In [19]:
print(a)

['SDG 1 - End poverty in all its forms everywhere'
 'SDG 2 - End hunger, achieve food security and improved nutrition and promote sustinable agriculture'
 'SDG 3: Ensure Healthy Lives and Well-Being for all at all ages'
 'SDG 4: Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all'
 'SDG 5: Achieve gender equality and empower all women and girls'
 'SDG 6: Ensure availability and sustainable management of water and sanitation for all'
 'SDG 7: Ensure access to affordable, reliable, sustainable and modern energy for all'
 'SDG 8: Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all'
 'SDG 9: Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation'
 'SDG 10: Reduce inequality within and among countries'
 'SDG 11: Make cities and human settlements inclusive, safe, resilient and sustainable'
 'SDG 15: Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss'
 'SDG 16: Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels']

In [20]:
longgoal = {1:'End poverty in all its forms everywhere', 
            2:'End hunger, achieve food security and improved nutrition and promote sustinable agriculture', 
            3:'Ensure Healthy Lives and Well-Being for all at all ages',
            4:'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all', 
            5:'Achieve gender equality and empower all women and girls',
           6:'Ensure availability and sustainable management of water and sanitation for all',
            7:'Ensure access to affordable, reliable, sustainable and modern energy for all',
            8:'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all',
           9:'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation',
            10:'Reduce inequality within and among countries',
            11:'Make cities and human settlements inclusive, safe, resilient and sustainable',
          15:'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss',
            16:'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels'}

In [21]:
data3['SDG GoalLong'] = data3['SDG'].map(longgoal)

In [22]:
data3.head(50)

,States_Uts,SDG,Indicator,Value,SDG GoalShort,SDG GoalLong
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved..."
7,A & N Islands,2,Ratio of rural households covered under public...,0.49,Zero Hunger,"End hunger, achieve food security and improved..."
8,A & N Islands,2,"Rice, wheat and coarse cereals produced annual...",2211.38,Zero Hunger,"End hunger, achieve food security and improved..."
9,A & N Islands,3,Annual notification of Tuberculosis cases per ...,76,Good Health and Well-Being,Ensure Healthy Lives and Well-Being for all at...
10,A & N Islands,3,Children aged 12-23 months fully immunized (BC...,73.2,Good Health and Well-Being,Ensure Healthy Lives and Well-Being for all at...
11,A & N Islands,3,"Number of governmental physicians, nurses and ...",16.43,Good Health and Well-Being,Ensure Healthy Lives and Well-Being for all at...
12,A & N Islands,3,"Under-five mortality rate per 1,000 live births",13,Good Health and Well-Being,Ensure Healthy Lives and Well-Being for all at...
13,A & N Islands,4,Adjusted Net Enrolment Ratio at Elementary (C...,77.48,Quality Education,Ensure inclusive and equitable quality educati...
14,A & N Islands,4,Average Annual Drop-out rate at secondary leve...,9.87,Quality Education,Ensure inclusive and equitable quality educati...
15,A & N Islands,4,Children in the age group of 6-13 who are out ...,2.12,Quality Education,Ensure inclusive and equitable quality educati...
16,A & N Islands,4,Correct responses on Learning Outcomes in Lang...,52,Quality Education,Ensure inclusive and equitable quality educati...
17,A & N Islands,4,Correct responses on Learning Outcomes in Lang...,39,Quality Education,Ensure inclusive and equitable quality educati...
18,A & N Islands,4,Elementary and secondary schools with Pupil Te...,99.51,Quality Education,Ensure inclusive and equitable quality educati...
19,A & N Islands,4,School teachers professionally qualified (%),98.86,Quality Education,Ensure inclusive and equitable quality educati...
20,A & N Islands,5,Average female to male ratio of average wages/...,1,Gender Equality,Achieve gender equality and empower all women ...
21,A & N Islands,5,Married women aged 15-49 who have ever experie...,19.6,Gender Equality,Achieve gender equality and empower all women ...
22,A & N Islands,5,Ratio of Female Labour force participation rat...,0.41,Gender Equality,Achieve gender equality and empower all women ...
23,A & N Islands,5,Women in the age group of 15-49 years using mo...,50.8,Gender Equality,Achieve gender equality and empower all women ...
24,A & N Islands,6,Annual ground water withdrawal against net ann...,0.98,Clean Water and Sanitation,Ensure availability and sustainable management...
25,A & N Islands,6,Districts verified to be Open Defecation Free (%),0,Clean Water and Sanitation,Ensure availability and sustainable management...
26,A & N Islands,6,Population having safe and adequate drinking w...,88.7,Clean Water and Sanitation,Ensure availability and sustainable management...
27,A & N Islands,6,Rural households with individual household toi...,100,Clean Water and Sanitation,Ensure availability and sustainable management...
28,A & N Islands,7,Households using Clean Cooking Fuel (%),63.5,Affordable and Clean Energy,"Ensure access to affordable, reliable, sustain..."
29,A & N Islands,7,Renewable share of installed generating capaci...,22.77,Affordable and Clean Energy,"Ensure access to affordable, reliable, sustain..."
30,A & N Islands,8,Annual growth rate of GDP per capita (at const...,7.06,Decent Work and Economic Growth,"Promote sustained, inclusive and sustainable e..."
31,A & N Islands,8,Average unemployment rate per 1000 persons for...,189.5,Decent Work and Economic Growth,"Promote sustained, inclusive and sustainable e..."
32,A & N Islands,8,Households with a bank account (%),100,Decent Work and Economic Growth,"Promote sustained, inclusive and sustainable e..."
33,A & N Islands,8,"Number of ATMs per 1,00,000 population",25.03,Decent Work and Economic Growth,"Promote sustained, inclusive and sustainable e..."
34,A & N Islands,9,Gram Panchayats covered under Bharat Net (%),0,Industry Innovation and Infrastructure,"Build resilient infrastructure, promote inclus..."
35,A & N Islands,10,Palma Ratio of Household Expenditure in Rural ...,0.98,Reduced Inequalities,Reduce inequality within and among countries
36,A & N Islands,10,Palma Ratio of Household Expenditure in Urban ...,1.76,Reduced Inequalities,Reduce inequality within and among countries
37,A & N Islands,10,Tribal Sub Plan fund utilised (%),155.4,Reduced Inequalities,Reduce inequality within and among countries
38,A & N Islands,11,Urban households living in slums (%),3.72,Sustainable Cities and Communities,"Make cities and human settlements inclusive, s..."
39,A & N Islands,11,Wards with 100% door to door waste collection (%),100,Sustainable Cities and Communities,"Make cities and human settlements inclusive, s..."
40,A & N Islands,11,Waste processed (%),23,Sustainable Cities and Communities,"Make cities and human settlements inclusive, s..."
41,A & N Islands,15,Change in estimated population of wild elephan...,Null,Life on Land,"Protect, restore and promote sustainable use o..."
42,A & N Islands,15,Change in forest area from 2015 to 2017 (%),-0.11,Life on Land,"Protect, restore and promote sustainable use o..."
43,A & N Islands,15,Decadal change in extent of water bodies withi...,-15.14,Life on Land,"Protect, restore and promote sustainable use o..."
44,A & N Islands,15,Total land area covered under forest (%),81.73,Life on Land,"Protect, restore and promote sustainable use o..."
45,A & N Islands,16,Births registered (%),79.3,Peace Justice and Strong Institutions,Promote peaceful and inclusive societies for s...
46,A & N Islands,16,Estimated number of courts per 10 Lakh persons,28.05,Peace Justice and Strong Institutions,Promote peaceful and inclusive societies for s...
47,A & N Islands,16,Estimated reported corruption crimes per 1 cro...,0.3,Peace Justice and Strong Institutions,Promote peaceful and inclusive societies for s...
48,A & N Islands,16,Population covered under Aadhaar (%),95,Peace Justice and Strong Institutions,Promote peaceful and inclusive societies for s...
49,A & N Islands,16,Reported cognizable crimes against children pe...,61.4,Peace Justice and Strong Institutions,Promote peaceful and inclusive societies for s...

In [23]:
data3.shape

(2174, 6)

In [ ]:
#data = a[0].split()
#print(data[1:])

In [ ]:
'''target = {}
for data in a:
    d = data.split(" ")
    #key = int(d[0].split()[1].replace(":",""))
    print(d)'''

In [24]:
data3.head()

,States_Uts,SDG,Indicator,Value,SDG GoalShort,SDG GoalLong
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere

In [ ]:
#data2.to_csv('data.csv')

In [25]:
indicators = pd.read_excel(open('F:/Pykih/SDG Data/Goals, Target, and Indicators.xlsx','rb'),sheet_name='Targets')

In [26]:
indicators.head(50)

   Target                                        Description
0     1.1  By 2030, eradicate extreme poverty for all peo...
1     1.2  By 2030, reduce at least by half the proportio...
2     1.3  Implement nationally appropriate social protec...
3     1.4  By 2030, ensure that all men and women, in par...
4     1.5  By 2030, build the resilience of the poor and ...
5     1.a  Ensure significant mobilization of resources f...
6     1.b  Create sound policy frameworks at the national...
7     2.1  By 2030, end hunger and ensure access by all p...
8     2.2  By 2030, end all forms of malnutrition, includ...
9     2.3  By 2030, double the agricultural productivity ...
10    2.4  By 2030, ensure sustainable food production sy...
11    2.5  By 2020, maintain the genetic diversity of see...
12    2.a  Increase investment, including through enhance...
13    2.b  Correct and prevent trade restrictions and dis...
14    2.c  Adopt measures to ensure the proper functionin...
15    3.1  By 2030, reduce the global maternal mortality ...
16    3.2  By 2030, end preventable deaths of newborns an...
17    3.3  By 2030, end the epidemics of AIDS, tuberculos...
18    3.4  By 2030, reduce by one third premature mortali...
19    3.5  Strengthen the prevention and treatment of sub...
20    3.6  By 2020, halve the number of global deaths and...
21    3.7  By 2030, ensure universal access to sexual and...
22    3.8  Achieve universal health coverage, including f...
23    3.9  By 2030, substantially reduce the number of de...
24    3.a  Strengthen the implementation of the World Hea...
25    3.b  Support the research and development of vaccin...
26    3.c  Substantially increase health financing and th...
27    3.d  Strengthen the capacity of all countries, in p...
28    4.1  By 2030, ensure that all girls and boys comple...
29    4.2  By 2030, ensure that all girls and boys have a...
30    4.3  By 2030, ensure equal access for all women and...
31    4.4  By 2030, substantially increase the number of ...
32    4.5  By 2030, eliminate gender disparities in educa...
33    4.6  By 2030, ensure that all youth and a substanti...
34    4.7  By 2030, ensure that all learners acquire the ...
35    4.a  Build and upgrade education facilities that ar...
36    4.b  By 2020, substantially expand globally the num...
37    4.c  By 2030, substantially increase the supply of ...
38    5.1  End all forms of discrimination against all wo...
39    5.2  Eliminate all forms of violence against all wo...
40    5.3  Eliminate all harmful practices, such as child...
41    5.4  Recognize and value unpaid care and domestic w...
42    5.5  Ensure womenâ€™s full and effective participat...
43    5.6  Ensure universal access to sexual and reproduc...
44    5.a  Undertake reforms to give women equal rights t...
45    5.b  Enhance the use of enabling technology, in par...
46    5.c  Adopt and strengthen sound policies and enforc...
47    6.1  By 2030, achieve universal and equitable acces...
48    6.2  By 2030, achieve access to adequate and equita...
49    6.3  By 2030, improve water quality by reducing pol...

In [27]:
number = list(indicators['Target'])
target_lists = []
i = 0
for num in number:
    strin_number = str(num).strip()
    strin_number = strin_number.split(".")
    strin_number = strin_number[0]
    target_lists.append(int(strin_number))

a = target_lists
indicators['SDG'] = a

In [28]:
indicators.head()

  Target                                        Description  SDG
0    1.1  By 2030, eradicate extreme poverty for all peo...    1
1    1.2  By 2030, reduce at least by half the proportio...    1
2    1.3  Implement nationally appropriate social protec...    1
3    1.4  By 2030, ensure that all men and women, in par...    1
4    1.5  By 2030, build the resilience of the poor and ...    1

In [29]:
indicators.shape

(169, 3)

In [30]:
final_data= data3.join(indicators.set_index('SDG'), on='SDG')

In [31]:
final_data.head(50)

,States_Uts,SDG,Indicator,Value,SDG GoalShort,SDG GoalLong,Target,Description
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.1,"By 2030, eradicate extreme poverty for all peo..."
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.2,"By 2030, reduce at least by half the proportio..."
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.3,Implement nationally appropriate social protec...
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.4,"By 2030, ensure that all men and women, in par..."
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.5,"By 2030, build the resilience of the poor and ..."
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.a,Ensure significant mobilization of resources f...
0,A & N Islands,1,Households with any usual member covered by an...,5.7,No Poverty,End poverty in all its forms everywhere,1.b,Create sound policy frameworks at the national...
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.1,"By 2030, eradicate extreme poverty for all peo..."
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.2,"By 2030, reduce at least by half the proportio..."
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.3,Implement nationally appropriate social protec...
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.4,"By 2030, ensure that all men and women, in par..."
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.5,"By 2030, build the resilience of the poor and ..."
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.a,Ensure significant mobilization of resources f...
1,A & N Islands,1,"Number of homeless households per 10,000 house...",0.97,No Poverty,End poverty in all its forms everywhere,1.b,Create sound policy frameworks at the national...
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.1,"By 2030, eradicate extreme poverty for all peo..."
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.2,"By 2030, reduce at least by half the proportio..."
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.3,Implement nationally appropriate social protec...
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.4,"By 2030, ensure that all men and women, in par..."
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.5,"By 2030, build the resilience of the poor and ..."
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.a,Ensure significant mobilization of resources f...
2,A & N Islands,1,Persons provided employment as a percentage of...,92.46,No Poverty,End poverty in all its forms everywhere,1.b,Create sound policy frameworks at the national...
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.1,"By 2030, eradicate extreme poverty for all peo..."
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.2,"By 2030, reduce at least by half the proportio..."
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.3,Implement nationally appropriate social protec...
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.4,"By 2030, ensure that all men and women, in par..."
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.5,"By 2030, build the resilience of the poor and ..."
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.a,Ensure significant mobilization of resources f...
3,A & N Islands,1,Population living below National Poverty line (%),1,No Poverty,End poverty in all its forms everywhere,1.b,Create sound policy frameworks at the national...
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.1,"By 2030, eradicate extreme poverty for all peo..."
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.2,"By 2030, reduce at least by half the proportio..."
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.3,Implement nationally appropriate social protec...
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.4,"By 2030, ensure that all men and women, in par..."
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.5,"By 2030, build the resilience of the poor and ..."
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.a,Ensure significant mobilization of resources f...
4,A & N Islands,1,Proportion of the population (out of total eli...,1.4,No Poverty,End poverty in all its forms everywhere,1.b,Create sound policy frameworks at the national...
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.1,"By 2030, end hunger and ensure access by all p..."
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.2,"By 2030, end all forms of malnutrition, includ..."
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.3,"By 2030, double the agricultural productivity ..."
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.4,"By 2030, ensure sustainable food production sy..."
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.5,"By 2020, maintain the genetic diversity of see..."
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.a,"Increase investment, including through enhance..."
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.b,Correct and prevent trade restrictions and dis...
5,A & N Islands,2,Children under age 5 years who are stunted (%),23.3,Zero Hunger,"End hunger, achieve food security and improved...",2.c,Adopt measures to ensure the proper functionin...
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.1,"By 2030, end hunger and ensure access by all p..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.2,"By 2030, end all forms of malnutrition, includ..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.3,"By 2030, double the agricultural productivity ..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.4,"By 2030, ensure sustainable food production sy..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.5,"By 2020, maintain the genetic diversity of see..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.a,"Increase investment, including through enhance..."
6,A & N Islands,2,Pregnant women aged 15-49 yrs who are anaemic ...,61.4,Zero Hunger,"End hunger, achieve food security and improved...",2.b,Correct and prevent trade restrictions and dis...

In [32]:
final_data.shape

(21137, 8)

In [33]:
columnsTitles = ['SDG', 'SDG GoalShort', 'SDG GoalLong','Target','Description','Indicator','States_Uts','Value']

final_data = final_data.reindex(columns=columnsTitles)

In [34]:
final_data.head()

,SDG,SDG GoalShort,SDG GoalLong,Target,Description,Indicator,States_Uts,Value
0,1,No Poverty,End poverty in all its forms everywhere,1.1,"By 2030, eradicate extreme poverty for all peo...",Households with any usual member covered by an...,A & N Islands,5.7
0,1,No Poverty,End poverty in all its forms everywhere,1.2,"By 2030, reduce at least by half the proportio...",Households with any usual member covered by an...,A & N Islands,5.7
0,1,No Poverty,End poverty in all its forms everywhere,1.3,Implement nationally appropriate social protec...,Households with any usual member covered by an...,A & N Islands,5.7
0,1,No Poverty,End poverty in all its forms everywhere,1.4,"By 2030, ensure that all men and women, in par...",Households with any usual member covered by an...,A & N Islands,5.7
0,1,No Poverty,End poverty in all its forms everywhere,1.5,"By 2030, build the resilience of the poor and ...",Households with any usual member covered by an...,A & N Islands,5.7

In [35]:
final_data.shape

(21137, 8)

In [36]:
# convert csv to xlsx file
writer = pd.ExcelWriter('SDG India Index Complete data.xlsx')
final_data.to_excel(writer, index = False)
writer.save()

In [2]:
import pandas as pd
metadata = pd.read_csv('F:/Pykih/SDG Metadata/sdg_index_meta.csv')

In [3]:
metadata.head()

,SNO,Goal,Indicator,Indicator Data Source,Computation Approach,Data Period,Number of States/UTs covered,Data Periodicity,Relevant UN Target,Relevant UN Indicator,Relevant MoSPI Indicator,Indicator Interpretation,Code
0,1,SDG 1 - End poverty in all its forms everywhere,Percentage of population living below National...,NITI Aayog [Tendulkar Committee Estimates],Directly from data source,2011-2012,35,Non-Periodic,"1.2: By 2030, reduce at least by half the prop...",1.2.1: Proportion of population living below t...,1.1.1: Proportion of population living below t...,Higher value means lower performance (-),1.01.01
1,2,SDG 1 - End poverty in all its forms everywhere,Percentage of households with any usual member...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,1.3: Implement nationally appropriate social p...,1.3.1: Proportion of population covered by soc...,1.3.1: Percentage of households with any usual...,Higher value means higher performance (+),1.03.01
2,3,SDG 1 - End poverty in all its forms everywhere,Persons provided employment as a percentage of...,Ministry of Rural Development [MGNREGA Progres...,(Persons provided employment under MGNREGA)×10...,2017-18,32,Annual,1.3: Implement nationally appropriate social p...,1.3.1: Proportion of population covered by soc...,1.3.3: Proportion of the population (out of to...,Higher value means higher performance (+),1.03.03
3,4,SDG 1 - End poverty in all its forms everywhere,Proportion of the population (out of total eli...,Ministry of Health and Family Welfare [Nationa...,Directly from data source,2015-16,36,3 Years,1.3: Implement nationally appropriate social p...,1.3.1: Proportion of population covered by soc...,1.3.5: Proportion of the population (out of to...,Higher value means higher performance (+),1.03.05
4,5,SDG 1 - End poverty in all its forms everywhere,"Number of homeless households per 10,000 house...",Numerator: Ministry of Rural Development [Soci...,"Number of homeless households per 10,000 house...",2011-12,36,10 Years,"1.4: By 2030, ensure that all men and women, i...",NaN,1.4.4: Proportion of homeless population to to...,Higher value means lower performance (-),1.04.04

In [4]:
# convert csv to xlsx file
writer = pd.ExcelWriter('sdg_index_meta.xlsx')
metadata.to_excel(writer, index = False)
writer.save()